# Define the namespace (if it does not already exist)

apiVersion: apps/v1

kind: Namespace

metadata:

  name: monitor-promo

---

# Define the ConfigMap for Prometheus configuration

apiVersion: v1

kind: ConfigMap

metadata:

  name: prometheus-config

  namespace: monitor-promo

data:

  prometheus.yml: |

    global:

      scrape_interval: 15s

    scrape_configs:

      - job_name: 'prometheus'

        static_configs:

          - targets: ['localhost:9090']

---

# Define the Prometheus Deployment

apiVersion: apps/v1

kind: Deployment

metadata:

  name: prometheus

  namespace: monitor-promo

spec:

  replicas: 1

  selector:

    matchLabels:

      app: prometheus

  template:

    metadata:

      labels:

        app: prometheus

    spec:

      containers:

        - name: prometheus

          image: prom/prometheus:latest

          ports:

            - name: web

              containerPort: 9090

---

# Define the Prometheus Service

apiVersion: v1

kind: Service

metadata:

  name: prometheus

  namespace: monitor-promo

spec:

  type: NodePort

  ports:

    - port: 9090

      targetPort: 9090

      nodePort: 31090

  selector:

    app: prometheus

 
